dataset:
  name: 'your_dataset_name'  # Replace with actual dataset name
  batch_size: 32

model:
  type: '3d_vit'  # Options: '2d_vit', '3d_vit', '3d_cnn'
  num_labels: 4
  freeze_layers: true

training:
  max_epochs: 50
  learning_rate: 1e-4
  device: 'cuda'
  tensorboard_log_dir: './runs'

paths:
  log_dir: './logs'
  checkpoint_dir: './checkpoints'
  output_dir: './output'