dataset:
  name: 'your_dataset_name'  # Replace with actual dataset name
  batch_size: 32

model:
  type: '3d_vit'  # Options: '2d_vit', '3d_vit', '3d_cnn'
  num_labels: 4
  freeze_layers: true

training:
  max_epochs: 100
  learning_rate: 0.001
  device: 'cuda'
  seed: 42
  amp: true
  tensorboard_log_dir: './logs/tensorboard'
  checkpoint_dir: './checkpoints'
  lr_scheduler:
    factor: 0.1
    patience: 10
  early_stopping:
    patience: 15
    min_delta: 0.001

paths:
  log_dir: './logs'
  output_dir: './output'