model:
  type: '3d_vit'  # Default model type
  num_labels: 4

dataset:
  name: 'your_dataset_name'
  batch_size: 32

training:
  max_epochs: 50
  learning_rate: 1e-4

paths:
  log_dir: './logs'
  checkpoint_dir: './checkpoints'
  output_dir: './output'