name: alzheimers_detection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - cudatoolkit=11.3  # adjust based on your CUDA version
  - monai>=0.8.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - nibabel>=3.2.0
  - pillow>=8.3.0
  - scikit-learn>=0.24.0
  - pandas>=1.3.0
  - tensorboard>=2.6.0
  - pip
  - pip:
    - -r requirements.txt